# Generated by Django 2.0.6 on 2018-09-05 09:27

from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_course_name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, storage=portal.models.MediaFileSystemStorage, upload_to='images//')),
                ('file', models.FileField(blank=True, null=True, storage=portal.models.MediaFileSystemStorage, upload_to='docs//')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Category'),
        ),
    ]
